name: build and release

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
          - Debug
          - RelWithDebInfo
        platform:
          - Win32
          - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: CMake Configure
        uses: threeal/cmake-action@v2.0.0
        with:
          run-build: false
          source-dir: drltrace_src
          build-dir: build
          args: "-A ${{ matrix.platform }}"
          options: |
            CMAKE_BUILD_TYPE=${{ matrix.config }}
            BUILD_TOOL_TESTS=ON
            CMAKE_CXX_FLAGS="/utf-8"
            CMAKE_C_FLAGS="/utf-8"

      - name: Build
        run: |
          cd build
          cmake --build . --config "${{ matrix.config }}"
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.config }}-${{ matrix.platform }}
          path: |
            build/bin*/
            build/dynamorio/logs/
            build/dynamorio/bin*/
            build/dynamorio/lib*/
            !build/dynamorio/libutil/

      - name: Run tests
        run: |
          ctest -VV
        shell: cmd

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: mkdir dist

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-RelWithDebInfo-Win32
          path: dist/drltrace-RelWithDebInfo-Win32

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-RelWithDebInfo-x64
          path: dist/drltrace-RelWithDebInfo-x64

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-Debug-Win32
          path: dist/drltrace-Debug-Win32

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-Debug-x64
          path: dist/drltrace-Debug-x64

      - run: |
          (cd dist && zip -r drltrace-RelWithDebInfo-Win32.zip ./drltrace-RelWithDebInfo-Win32)
          (cd dist && zip -r drltrace-RelWithDebInfo-x64.zip ./drltrace-RelWithDebInfo-x64)
          (cd dist && zip -r drltrace-Debug-Win32.zip ./drltrace-Debug-Win32)
          (cd dist && zip -r drltrace-Debug-x64.zip ./drltrace-Debug-x64)

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/drltrace-*.zip
